version: '3'
services:
  issuer:
    image: acapy-vc-holder-demo
    platform: linux/amd64
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      RUST_LOG: warn
      KMS_BASE_URL: http://kms
    command: >
      start
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://issuer:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --emit-new-didcomm-prefix
        --wallet-name demo
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --plugin acapy_vc_holder
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      kms:
        condition: service_started

  kms:
    image: ghcr.io/dbluhm/mini-kms:0.1.2
    platform: linux/amd64
    ports:
      - "8080:80"

  demo:
    image: acapy-vc-holder-demo-runner
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./demo/Dockerfile
    environment:
      AGENT: http://issuer:3001
    depends_on:
      issuer:
        condition: service_healthy
